# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.9.0"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.9/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
Linux Firmware: 20241210
stargz-snapshotter: 0.16.3
ecr-credential-provider: 0.31.4
wasm-edge: 0.5.0
crun: 1.19.1
qemu-guest-agent: 9.2.0
Tailscale: 1.78.1
"""

[make_deps]
